theme = "mytheme"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
bufferline = "multiple"

[keys.normal]
C-s = ":w"
C-a = "select_all"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
