[[language]]
name = "python"
language-servers = ["pyright"]
roots = ["pyproject.toml", "Poetry.lock", ".git"]
formatter = {command = "black", args = ["--quiet", "-"]}
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
